### ISSUE TITLE
crosstalk version needed?

### ISSUE THREAD

**Issue by bgweber** [cpsievert/zikar#1]
I'm getting the following error when trying to install the package: 
Error: Malformed remote specification 'rstudio/crosstalk

> packageVersion("crosstalk")
> [1] ‘0.2’
> devtools::install_github("cpsievert/zikar")
> Downloading GitHub repo cpsievert/zikar@master
> Installing zikar
> Error: Malformed remote specification 'rstudio/crosstalk
> jcheng5/plotly@joe/feature/crosstalk'

What are the package prerequisites for this tool? I reinstalled crosstalk using: 
devtools::install_github("rstudio/crosstalk")

Thanks,
Ben

**Comment by cpsievert** [comment]
Ah, I think I was missing a comma, can you try again?

**Comment by cpsievert** [comment]
If you run into problems again, try:

``` r
devtools::install_github("rstudio/crosstalk")
devtools::install_github("jcheng5/plotly@joe/feature/crosstalk")
```

**Comment by bgweber** [comment]
Thanks for the help! Looks like this might be an issue with installing cross talk:

> devtools::install_github("jcheng5/plotly@joe/feature/crosstalk")
> Downloading GitHub repo jcheng5/plotly@joe/feature/crosstalk
> Installing plotly
> Error: Malformed remote specification 'rstudio/crosstalk'

I'll follow up on the crosstalk page.
